services:
  2026-1-stage3-t2-program-backend:
    image: ${DOCKER_IMAGE:-2026-1-stage3-t2-program-backend:latest}
    container_name: 2026-1-stage3-t2-program-backend
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
